### ISSUE TITLE
Bug in Chapter 7 Fragment Rotation

### ISSUE THREAD

**Issue by j8s0n** [dogriffiths/HeadFirstAndroid#3]
With the fix code from the section "Rotating the device breaks the app", there's still a rotation bug.
Put a few items in the back stack, rotate the device *twice*, then go through the back stack. Everything is defaulting to the 0 index item.
The problem is Fragment.onCreateView() only gets called for the visible fragment. So when you rotate it the second time, the hidden fragments don't have the proper value to write to the bundle, and end up writing 0.
I moved the code to retrieve the value from the saved Bundle to onCreate(), which gets called for the hidden and visible fragments, and it functions properly.

**Comment by dogriffiths** [comment]
Thanks for reporting that. We’ll take a look this weekend.

**Comment by dogriffiths** [comment]
This is now fixed. The code was also wrong in the chapter 8 version of the workout bug. You can see the fix in this commit:

014e30afabb6dfa9590371c577d44c7d90ed6348

There is a reprint due of the book in January. The code will be updated for chapters 7/8 and will be available in the paperback and ebook versions at that time.

Thanks once again for spotting this :-) Hopefully it didn’t spoil your enjoyment of the book too much.

**Comment by axxis1999** [comment]
Why did you move the fragment transaction to the else branch?
