### ISSUE TITLE
Chapter 13 Odometer Request Dangerous Permissions for Marshmallow Causes Crash

### ISSUE THREAD

**Issue by TBVanderley4545** [dogriffiths/HeadFirstAndroid#4]
When requesting permission for ACCESS_FINE_LOCATION, Android has declared this as "Protection Level: Dangerous", which means that starting with Android Marshmallow, the app must explicitly ask the user for permission before it can be used. 

Because there wasn't a request for permission, this app crashes immediately on devices running Android Marshmallow. I have a solution that I believe is working correctly here: [https://github.com/TBVanderley4545/Odometer.git](url). I added checkSelfPermissions in onCreate and onStart in MainActivity.java and implemented onRequestPermissionResult. I also added checkSelfPermission in OdometerService.java in onCreate() and onDestroy().

Thank you for writing your book. It's been a great help.

**Comment by TBVanderley4545** [comment]
Sorry, the link didn't work the first time. [https://github.com/TBVanderley4545/Odometer.git](https://github.com/TBVanderley4545/Odometer.git)

**Comment by dogriffiths** [comment]
Hi! Good catch :-)

I believe this should only be a problem if the targetSdkVersion in the app/build.gradle is set to 23. Prior to that level, I *believe* there won’t be a problem. 
The code in the book currently sets the target SDK back a little, so the issue should not arise with the code from there. For that reason, I won’t update the code on this repo.

However... Android Studio may generate projects with a targetSdkVersion set to 23, so we will add a couple of additional pages to the book to explain the consequences of moving to API 23, with the new permissions model.

Thanks so much for reporting this :-)

DG
