### ISSUE TITLE
Gradle project sync error when importing stopwatch project

### ISSUE THREAD

**Issue by tomjohnson1492** [dogriffiths/HeadFirstAndroid#6]
I imported the Stopwatch project from chapter 4 into Android Studio, but it creates an error: "Grade project sync failed. Basic functionality (e.g., editing, debugging) will not work properly." Any ideas on how to fix this?

**Comment by dogriffiths** [comment]
Hello Tom,

Have you tried right-clicking the build.grade file in “app” and then choosing the synchronise option?

What version of Android Studio are you using?

DG

**Comment by tomjohnson1492** [comment]
Yes, I tried the resync option based on the Android Studio prompts, but it didn't work. Neither did restarting.

I'm using Android Studio 2.0.

**Comment by dogriffiths** [comment]
Hello Tom,

I opened the project in Android Studio 2.0 and I got exactly the same error. The problem appears to be that Android Studio 2 requires gradle version 2.10 to do its build. I’ve pushed back a fix to this, and all the other projects. You can get this by doing a

    git pull

or else by doing a fresh checkout.

Thanks very much for spotting and reporting this :-)

Regards,

DG

**Comment by tomjohnson1492** [comment]
Thanks! I pulled the latest and it works perfectly now.
